# Generated by Django 3.1.7 on 2021-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tblmasuratori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umiditate', models.IntegerField(blank=True, db_column='Umiditate', null=True)),
                ('temperatura', models.IntegerField(blank=True, db_column='Temperatura', null=True)),
                ('presiune', models.IntegerField(blank=True, db_column='Presiune', null=True)),
                ('altitudine', models.IntegerField(blank=True, db_column='Altitudine', null=True)),
                ('timp', models.IntegerField(blank=True, db_column='Timp', null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tblmasuratori',
            },
        ),
    ]
